### ISSUE TITLE
Timer subscription doesn't fire in response to URL change

### ISSUE THREAD

**Issue by klazuka** [elm/core#980] opened 2018-09-04 20:20 UTC
While porting my app to 0.19, I found that my page loading bar timer was working only on initial load—after changing the "page", the timer subscription would not fire again.

# SSCCE

Here's the best I could do to recreate it in an SSCCE:

```elm
import Browser exposing (UrlRequest)
import Browser.Events
import Browser.Navigation as Nav
import Html exposing (a, div, h1, text)
import Html.Attributes exposing (href)
import Time
import Url exposing (Url)


main =
    Browser.application
        { init = init
        , view = view
        , update = update
        , subscriptions = subscriptions
        , onUrlRequest = ClickedLink
        , onUrlChange = UrlChanged
        }


type alias Model =
    { count : Int
    , navKey : Nav.Key
    , isRunning : Bool
    }


init : () -> Url -> Nav.Key -> ( Model, Cmd Msg )
init _ url key =
    ( loadPage url
        { count = 0
        , isRunning = False
        , navKey = key
        }
    , Cmd.none
    )


type Msg
    = Tick Time.Posix
    | ClickedLink UrlRequest
    | UrlChanged Url


update msg model =
    case msg of
        Tick _ ->
            ( { model | count = model.count + 1 }, Cmd.none )

        ClickedLink req ->
            case req of
                Browser.Internal url ->
                    ( model, Nav.pushUrl model.navKey (Url.toString url) )

                Browser.External href ->
                    ( model, Nav.load href )

        UrlChanged url ->
            ( loadPage url model, Cmd.none )


loadPage url model =
    { model | isRunning = url.fragment == Just "/timer" }


subscriptions : Model -> Sub Msg
subscriptions model =
    if model.isRunning then
        Browser.Events.onAnimationFrame Tick

    else
        Sub.none


view model =
    { title = ""
    , body =
        [ text (String.fromInt model.count)
        , if model.isRunning then
            div []
                [ h1 [] [ text "Running" ]
                , a [ href "/" ] [ text "stop" ]
                ]

          else
            div []
                [ h1 [] [ text "Idle" ]
                , a [ href "#/timer" ] [ text "start" ]
                ]
        ]
    }
```

I would have made it smaller, but the bug only appears to occur when the `subscription` function is called in response to an `update` triggered by `Browser.application`'s `onUrlChange` event.

## Expected Behavior

When you click the "start" link in the above example app, the counter should start increasing 60 times per second.

## Actual Behavior

After clicking "start", the counter is stuck at 0.

## Analysis

As best I can tell, the `subscription` is getting called at the right time, but the Elm runtime seems to be ignoring the subscription value returned by my code. I suspect the bug is similar to https://github.com/elm/compiler/issues/1776 which also reports subscriptions getting ignored.

# Additional Notes

Replacing `Browser.Events.onAnimationFrame Tick` with `Time.every 16 Tick` appears to fix the bug. Although in my real application which I first experienced the bug in, it doesn't make any difference whether I use the animation-frame timer vs `Time.every`—they both get stuck.

**Comment by evancz** [comment] 2019-12-05 00:28
Thank you for the SSCCE! It looks like this is fixed by https://github.com/elm/core/commit/704dcc08d4617d45c8b0fce7a68729335c880756. When I try your example with my local build, I am seeing the expected behavior.

This should come out in elm/core 1.0.3 along with a couple other fixes and improvements.

**Closed by evancz** 2019-12-05 00:28 UTC
